version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/service_based_assessment_db
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_USER: service_based_assessment_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: service_based_assessment_db
